package model;
// Generated Apr 26, 2014 4:39:36 PM by Hibernate Tools 3.6.0



/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int staus;

    public Roles() {
    }

    public Roles(String name, int staus) {
       this.name = name;
       this.staus = staus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getStaus() {
        return this.staus;
    }
    
    public void setStaus(int staus) {
        this.staus = staus;
    }




}


