package model;
// Generated Apr 26, 2014 4:39:36 PM by Hibernate Tools 3.6.0



/**
 * Techniques generated by hbm2java
 */
public class Techniques  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int status;

    public Techniques() {
    }

    public Techniques(String name, int status) {
       this.name = name;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    
    public String id_to_name(int _id){
        String result = "unknown";
        if (_id == 1){
            result = ".net";
        }else if(_id == 2){
            result =  "AXIS2";
        }else if (_id == 3){
            result = "JAX-WS";
        }else if(_id == 4){
            result = "technique";
        }
        return result;
        
    }




}


