package model;
// Generated Apr 26, 2014 4:39:36 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private int fkRoleId;
     private String name;
     private String family;
     private String companyName;
     private String email;
     private String website;
     private String logoUrl;
     private Date registeredDate;
     private int status;
     private String password;

    public Users() {
    }

    public Users(int fkRoleId, String name, String family, String companyName, String email, String website, String logoUrl, Date registeredDate, int status, String password) {
       this.fkRoleId = fkRoleId;
       this.name = name;
       this.family = family;
       this.companyName = companyName;
       this.email = email;
       this.website = website;
       this.logoUrl = logoUrl;
       this.registeredDate = registeredDate;
       this.status = status;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFkRoleId() {
        return this.fkRoleId;
    }
    
    public void setFkRoleId(int fkRoleId) {
        this.fkRoleId = fkRoleId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFamily() {
        return this.family;
    }
    
    public void setFamily(String family) {
        this.family = family;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getLogoUrl() {
        return this.logoUrl;
    }
    
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
    public Date getRegisteredDate() {
        return this.registeredDate;
    }
    
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


