package model;
// Generated Apr 26, 2014 4:39:36 PM by Hibernate Tools 3.6.0



/**
 * Wsdl generated by hbm2java
 */
public class Wsdl  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private int fkOwnerId;
     private double price;
     private String url;
     private String subject;
     private String description;
     private int fkTechniquesId;
     private int status;
     private int fkCategoryId;
     private String CategoryName;
      private String TechniqueName;

    

    public Wsdl() {
    }

    public Wsdl(int fkOwnerId, double price, String url, String subject, String description, int fkTechniquesId, int status, int fkCategoryId) {
       this.fkOwnerId = fkOwnerId;
       this.price = price;
       this.url = url;
       this.subject = subject;
       this.description = description;
       this.fkTechniquesId = fkTechniquesId;
       this.status = status;
       this.fkCategoryId = fkCategoryId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFkOwnerId() {
        return this.fkOwnerId;
    }
    
    public void setFkOwnerId(int fkOwnerId) {
        this.fkOwnerId = fkOwnerId;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getFkTechniquesId() {
        return this.fkTechniquesId;
    }
    
    public void setFkTechniquesId(int fkTechniquesId) {
        this.fkTechniquesId = fkTechniquesId;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public int getFkCategoryId() {
        return this.fkCategoryId;
    }
    
    public void setFkCategoryId(int fkCategoryId) {
        this.fkCategoryId = fkCategoryId;
    }
    
     public String getCategoryName() {
        return CategoryName;
    }

    public void setCategoryName(String CategoryName) {
        this.CategoryName = CategoryName;
    }

    public String getTechniqueName() {
        return TechniqueName;
    }

    public void setTechniqueName(String TechniqueName) {
        this.TechniqueName = TechniqueName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    

}


